default_linux:
		clear;\
		rm inventory.db;\
		touch inventory.db;\
		gcc c.c sql.c -lsqlite3 -o c;\
		./c;


empty:
	clear;rm inventory.db; touch inventory.db

r:
	clear;rm inventory.db ; touch inventory.db; ./c
